### ISSUE TITLE
 Reverse domain name notation in package name

### ISSUE THREAD

**Issue by skibitsky** [BennyKok/unity-searchable-event-drawer#1]
Hello,

The [package name](https://github.com/BennyKok/unity-searchable-event-drawer/blob/master/package.json#L2) in `package.json` should conform to reverse domain name notation with at least 3 components (tld.org-name.pkg-name). 

[Unity - Manual:  Package manifest](https://docs.unity3d.com/Manual/upm-manifestPkg.html#name)
[Unity - Manual:  Naming your package](https://docs.unity3d.com/Manual/cus-naming.html)

**Comment by BennyKok** [comment]
Thanks for reminding! Fixed it just now
